# Generated by Django 3.1.7 on 2021-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratesnumber',
            name='rates_number',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, max_length=10, verbose_name='rates_number'),
        ),
    ]
