# Generated by Django 3.1.7 on 2021-03-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210328_1436'),
    ]

    operations = [
    ]
