# Generated by Django 3.1.7 on 2021-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210328_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratesnumber',
            name='rates_number',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=0, verbose_name='rates_number'),
        ),
    ]
